### ISSUE TITLE
semantic scene segmentation

### ISSUE THREAD

**Issue by samanehAb** [ricvolpi/generalize-unseen-domains#2]
Hello,
I was wondering if you also share the codes for the semantic segmentation task.

**Comment by ricvolpi** [comment]
Hi, I will release it asap. 

In the meanwhile, here some code to load SYNTHIA dataset: https://github.com/ricvolpi/semantic-segmentation-SYNTHIA/blob/master/load_synthia.py

The dataset can be downloaded here: http://synthia-dataset.net/download-2

Anyway, if you already have some code for semantic segmentation, integrating the ADA method should be reasonably simple by copying-and-pasting the one I released for MNIST.

**Comment by yixiaonaihe** [comment]
Hi~ ricvolpi. In your recent work <Continual Adaptation of Visual Representations via Domain Randomization and Meta-learning>, it is really nice. I have a question about the digits expriments. All of them(mnist mnist-m syn svhn) use 10000 images for training, then how much test samples used for evaluation? Thx~ have a good day!
